### ISSUE TITLE
Change name of CSVelte\Input to CSVelte\Readable

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#13]
Since there is no longer a CSVelte\InputInterface interface, the name CSVelte\Input doesn't seem to fit any more. Maybe instead call it CSVelte\Readable or something along those lines.

**Comment by nozavroni** [comment]
Also considering using just an IO interface rather than Input/Output

**Comment by nozavroni** [comment]
Changed all of it to simply `IO\Stream`
