### ISSUE TITLE
Parameter order on Readable::readLine()

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#21]
I think it might make more sense to switch the parameter order on the Readable::readLine() interface from $maxLen, $lineTerminator to $lineTerminator, $maxLen because I've found that I rarely care about $maxLen but often find the need to change $lineTerminator. That may be because my use cases are wildly different than my end users though... think about it.

**Comment by nozavroni** [comment]
This will be rendered moot by issue #96 since Readable::readLine() has been changed to Readable::fgets() (or possibly getCurrentLine())

**Comment by nozavroni** [comment]
Fixed by several refactors
