### ISSUE TITLE
Make Readable/Writable traits rather than classes

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#38]
Rather than have Readable/Writable be their own classes, why not make them traits? Then have classes for File, Stream, etc. that just use Readable or Writable traits if they need to be readable/writable.

**Comment by nozavroni** [comment]
Definitely not getting rid of Readable/Writable interfaces, but still haven't decided yet whether or not I want to implement IsReadable and IsWritable traits. Probably not. Leaning towards no.

**Comment by nozavroni** [comment]
Not going to do this

**Comment by nozavroni** [comment]
Brought this back. Actually ended up implementing this... at least partially.

**Comment by nozavroni** [comment]
Implemented, tested (sort of). Not documented, but not going to be until later version.
