### ISSUE TITLE
Move CSVelte\Reader\Row* classes into CSVelte\Data\Row*

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#42]
As I was writing the CSV\Writer* classes, it became apparent that it would be beneficial to have a class to represent a row and a class to represent a column. When I was writing the Reader classes, it was useful to have similar classes so I created CSVelte\Row and a few others. Rather than keep this in the Reader namespace, move it into its own namespace so that I can use it anywhere. Name it something like CSVelte\Data\Row or CSVelte\Table\Row. Something like that.

**Comment by nozavroni** [comment]
This is finished
