### ISSUE TITLE
CSVelte and PHabulous/PHabular/Phab

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#44]
As I mentioned in the previous issue (#43), the vast majority of people searching for a CSV library for PHP aren't going to be interested in all the other crazy things this library does (aims to, anyway). Because of this, I have been considering actually making it a suite of smaller libraries rather than one big/medium-sized library. CSVelte itself would be only for working with traditional CSV data, as it were. There would then be a library called Phabulous or Phabular or maybe even just Phab that does all of the other tabular-data stuff outlined by the CSV on the Web working group. This is just an idea though. For now I'm just going to get CSVelte v0.0.1 out the door and if feature creep starts getting out of hand I'll reevaluate.

**Comment by nozavroni** [comment]
Marked as duplicate because I believe there's already another ticket like this assigned to v0.3 release... need to double check though.
