### ISSUE TITLE
memory/performance enhancements

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#5]
CSV files can potentially be enormous. It is important, while building this library, to remember never to load an entire file into memory. Functions such as file_get_contents() are unacceptable. Always read line by line or, at the very least, read in a finite amount of data and never **ALL** of it.

I opened this issue to keep track of all memory-saving, performance-related issues.

**Comment by deni-zen** [comment]
Check out this library and study how they handled stream wrappers. See if you can use any of that to implement I/O buffers and put together some sort of performance framework that tests memory usage, I/O hits, speed, etc. Maybe even use fancy javascript graphs just for the fun of it...

https://github.com/mikey179/vfsStream

**Comment by nozavroni** [comment]
This issue is too vague to be of any use whatsoever. Closing it.
