### ISSUE TITLE
Dependency handling for non-composer users

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#52]
CSVelte's only dependency (unless you want to run unit tests or generate API docs) is Carbon. And even that, I could probably eliminate pretty easily as a dependency. See if you can write the library in such a way that it will fail gracefully if Carbon is unavailable and update the docs to mention that Carbon is like a soft dependency.
- [ ] Use [burgomaster](https://github.com/mtdowling/Burgomaster) to generate phar, zip, and/or tarballs for every release 
- [ ] Integrate burgomaster with Travis-CI so that these are generated automatically for every release 
- [ ] Test it 
- [ ] Document it

**Comment by nozavroni** [comment]
Remove carbon as a dependency until data types are added

**Comment by nozavroni** [comment]
Putting this on the back-burner for now because I no longer have any dependencies (so it's not really a priority any more).
