### ISSUE TITLE
Allow array anywhere you allow flavor

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#54]
I want to accept an associative array containing flavor attributes anywhere that I accept a flavor object. And then internally the array will be converted to a flavor. For instance... 

``` php
<?php
$reader = CSVelte::reader('./files/data.csv', ['delimiter' => "\t", 'doubleQuotes' => false, 'escapeChar' => '\\']);
```

And then internally I would do this:

``` php
// ...

public static function reader($filename, $flavor)
{
    if (!($flavor instanceof Flavor)) {
        if (is_array($flavor)) $flavor = new Flavor($flavor);
    }
}

// ...

```
- [x] Update code to allow an assoc array anywhere you currently allow Flavor 
- [x] Unit tests 
- [x] Update docs
  - [x] Update docblocks for api docs

**Comment by deni-zen** [comment]
Actually in the Flavor class I should do something like this:

``` php
// ... 
public static function instance($flavor)
{
    if ($flavor instanceof Flavor) return $flavor;
    if (is_array($flavor)) return new Flavor($flavor);
    if ($flavor instanceof Iterator) {
        $flv = array();
        foreach ($flavor as $prop => $val) {
            $flv[$prop] = $val;
        }
        return new Flavor($flv);
    }
    // now throw exception cuz it cant do anything with $flavor
}
```

And then anywhere that expects a flavor could simply call $flavor = Flavor::instance($flavor);

**Comment by nozavroni** [comment]
Implemented and Scrutinized*
