### ISSUE TITLE
Figure out delivery process

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#57]
I need a process/tool to standardize my delivery process. When I do a release, I need to ensure that a particular set of steps are executed the same way every time and that all angles of the release are taken care of. I used to use phing back in the day but do a little research and see if phing is old man stuff these days or what...
- [Phing](https://www.phing.info/) - inspired by Apache ANT (it's what I used to use)
- [Robo](https://github.com/consolidation-org/Robo) - alternative to phing, supposedly inspired by gulp
- [bldr.io](http://bldr.io/) - Just another PHP task runner
- [Capistrano](http://capistranorb.com/) - A remote server automation and deployment tool written in Ruby (but apparently capable of deploying any language). [Webistrano](https://github.com/peritor/webistrano) is a Web UI for managing Capistrano deployments.

**These are interesting...**
- https://codeship.com/
- https://travis-ci.org/ - I signed up for this one 
- https://scrutinizer-ci.com/ - I signed up for this one too (Mockery appears to be using both)

**Comment by deni-zen** [comment]
This issue is _almost_ a duplicate of #59 but not quite. I'll leave it for now since this one lists all of the CI tools available.

**Comment by nozavroni** [comment]
I'm closing this because I've pretty much figured out how I want to go about deploying... just have to figure out the configuration details now. There are, however, a few items on this list that I would like to add to my research list on the wiki. See #71 as well.
