### ISSUE TITLE
plugin support?

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#6]
One idea I had, (although it may be overkill for such a small library) was to allow for the creation of plugins. For things such as skipping blank lines, filtering out certain lines/columns, replacing curse words with asterisks, etc. There could be reader plugins, writer plugins, and I don't know... maybe renderer plugins. Definitely something to think about.

**Comment by nozavroni** [comment]
This issue is too vague... there are plenty of ways to do these things anyway. If I decide I want some type of plugin support, I'll write a more detailed, more useful issue description in the future.
