### ISSUE TITLE
Integrate with Travis-CI

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#62]
I want to use Travis-CI to automate my release process. Do the research into how to use it and do whatever you have to do to integrate with it.
- [ ] Use [Burgomaster](https://github.com/mtdowling/Burgomaster) to automate package creation for non-composer users (see issue #52)
- [ ] Remove s3 download code for sample CSV files (I tried this before and it caused every test to fail) (see #3)

**Comment by deni-zen** [comment]
Try to eliminate as many dependencies as you can, even dev dependencies because Travis will have to download and install them. Rewrite your unit tests so that they dont require external shit other than phpunit.

**Comment by nozavroni** [comment]
This is an ongoing issue, removing milestone attachement.
