### ISSUE TITLE
Alternate PHP version support 

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#69]
As of right now CSVelte literally supports ONE version of PHP and that's PHP5.6. That is _**extremely**_ lame. I'll definitely want to support either/both of PHP all the way back to 5.3 or 5.4 and/or up to PHP7. PHP7 for sure. 

I would prefer not to have to do anything special to support PHP7 (I don't want to have to maintain a separate branch for PHP7 development) but I suppose I would if I had to. The only reason the PHP7 build is breaking right now is due to composer errors. Add the PHP7 allowed to fail directive to travis file. 

Also, look into HHVM. A lot of travis builds for PHP are including HHVM in their travis files. I'm not sure exactly how difficult or what it takes to support HHVM/Hack but I would like to do that as well if it's not too difficult.

**Comment by nozavroni** [comment]
Pushing to v0.2 I can't do anything about this for this release.

**Comment by nozavroni** [comment]
Changed supported versions to PHP5.6 && >= PHP7.0
