### ISSUE TITLE
Create a "Roadmap" document

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#73]
One thing I think would help me to not wander away from what is most important _right now_, is a road map. As detailed a roadmap as possible. I want to sketch out what I expect to have in version 0.1, 0.2, 0.3, etc. all the way up to version 1.0 or possibly even 2.0. I don't know if I want the roadmap in the docs or in the wiki or just in a ROADMAP file... probably the docs.
- https://github.com/deni-zen/csvelte/wiki/Roadmap

**Comment by nozavroni** [comment]
This is one of the few aspects of this library that can technically be worked on without even being on a computer. You can sit and jot down ideas for the roadmap in a notebook and then copy them over to the wiki. So this is a stupid issue to hold up a release for. Moving to v0.2.
