### ISSUE TITLE
Probably should use SplFile/SplFileInfo for I/O file classes

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#77]
Rather than just extending Stream, extend SplFileObject for your IO/File object. Here's whatcha need ta do: 
- [x] Add all methods from CSVelte\Contract\Readable
- [x] Add all methods from CSVelte\Contract\Writable
- [x] Add methods from CSVelte\Contract\Seekable?
- [x] Update the CSVelte class (it currently points to the old CSVelte\Input classes)
- [x] Update anywhere else in the code that uses the old CSVelte\Input* classes
- [ ] Throw exceptions for methods you don't want to be accessible to userland 
  - [ ] fgetcsv
  - [ ] fputcsv
  - [ ] getCsvControl - should actually use this (see below)
  - [ ] setCsvControl - should actually use this (see below)
  - [ ] setFlags?
- [x] When I first wrote the IO\File class I was looking at SplFileInfo::__construct() on PHP.net and thinking that there was only one arg to the constructor (filename) but there are several. But anyway, because of this, I added an $options param that allows me to set options I want on the file. Then I found out that many of those options were available as args to __construct. But at this point I had already written and tested the constructor with $options so I just went with it. I may end up having to remove it. 
- [ ] Don't forget to update the documentation

**Comment by nozavroni** [comment]
Complete/consider these first: 
- #13 ~~CSVelte\Input -> CSVelte\Readable and CSVelte\Output -> CSVelte\Writable~~ Decided to put everything under CSVelte\IO 
- #21 ~~Parameter order on Readable::readLine()~~ rendered moot by #77 and #96
- #24 ~~Seekable::seekToLine()~~ ignoring this one until it becomes necessary
- #38 ~~Make IsReadable and IsWritable traits~~ ignoring this one until I find a need for it as well 
- #78 ~~File modes should include "b" mode~~ I think this will be taken care of by #77 and #96 as well

**Comment by nozavroni** [comment]
The more I think about this the more I think extending SplFileObject the way I am is a bad idea. I think a better way to go would be to rewrite the Writable interface to fit with SplFileObject so that any SplFileObject can be passed to the Reader/Writer as-is. I could maybe write specialized versions of them just for clarity and to restrict access to certain methods or whatever, but you wouldn't have to use my file object(s). So basically I would just change the Readable interface to... 

**Readable**

``` php
interface Readable 
{
    public function fgets() (or getCurrentLine());
    public function fread($length);
    public function eof();
    public function rewind();
}
```

**Writable**

``` php
interface Writable 
{
    public function fwrite($string);
}
```

In fact I could probably still keep my CSVelte\IO\File object for convenience if I want it. But I just need ot adjust the interfaces. Probably want to add this one too:

**Seekable**

``` php
interface Seekable 
{
    public function fseek($pos);
}
```

**Comment by nozavroni** [comment]
The SplFileObject::setCsvControl() and getCsvControl methods should be incorperated somehow. Like when using IO\File, it should alter these methods to accept and return a Flavor object, and in the reader, if no flavor is set, then it should consult SplFileObject::getCsvControl

**Comment by nozavroni** [comment]
I think we can scrap CSVelte\IO\Stream (#97) for now... SplFileObject should work in its place AFAIK

This may be relevant: http://php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen

Also I don't know how, or even if its possible, to get the actual resource object of SplFileObject

**Comment by nozavroni** [comment]
Rather than having to go with some nonstandard duck-typing or instanceof solution I have decided (I think) to support (in a way) the reading of SplFileObject by creating an adapter. So you simply do this instead: 

``` php
$reader = CSVelte::readerFromSplFileObject($splFileObj);
```

or 

``` php
$file = CSVelte\IO\File::fromSplFileObject($obj);
```

**Comment by nozavroni** [comment]
Since I won't be able to accept SplFileObject directly, change the Readable, Writable, and Seekable methods back to `read()`, `write()`, `seek()`, etc.

**Comment by nozavroni** [comment]
The more I use this thing the more I feel restricted by it. Scrap it. Extend stream instead. It just works better. Provides way more flexibility.

**Comment by nozavroni** [comment]
Scrapped and removed.
