### ISSUE TITLE
Fix packagist / github names

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#80]
There are way too many different names I'm using on packagist and github. There's lukev, nozavroni, denizen deni-zen, denizengarden... just use nozavroni for everything. Transfer ownership of this project to nozavroni, delete the lukev/csvelte project on packagist, and submit this project as nozavroni/csvelte.
- [x] Change the composer package name to nozavroni/csvelte
- [x] Delete the old lukev/csvelte package from Packagist.org
- [x] Submit new nozavroni/csvelte package to Packagist.org
- [x] Transfer ownership of the csvelte Github repo to nozavroni
- [x] Update documentation and README and anywhere else that referenced the old lukev/csvelte package and change it to nozavroni/csvelte
- [x] Install csvelte using composer to make sure it works as expected (and as it shows in the documentation) - Tried this and it doesn't work. Needs to be changed to "composer require nozavroni/csvelte @dev-master" with an explanation of why 
- [x] Update csvelte.phpcsv.com subdomain DNS settings to reflect new ownership (should point to nozavroni.github.io)
- [x] Update Scrutinizer's Github URL
- [x] Update Travis-CI's Github URL
- [x] Update Coveralls Github URL
- [x] Update Google+ Github URL(s)
- [x] Update ReadTheDocs's Github/Composer URLs 
- [x] Update Google Groups (mailing list) with new URL

**Comment by nozavroni** [comment]
I deleted both nozavroni/csvelte and lukev/csvelte from packagist and am in the process of transferring this repo to nozavroni. Once its transferred to me, I'm going to resubmit it to packagist.

**Comment by nozavroni** [comment]
I finally got all this finished.
